# Generated by Django 5.1.3 on 2024-11-11 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina_personal', models.URLField(blank=True, max_length=255, null=True)),
                ('apodo', models.CharField(blank=True, max_length=50, null=True)),
                ('informacion_publica', models.BooleanField(default=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('organizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('pais_residencia', models.CharField(blank=True, max_length=100, null=True)),
                ('redes_sociales', models.JSONField(blank=True, default=dict)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
