# Generated by Django 5.1.3 on 2024-11-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.AddField(
            model_name='perfil',
            name='id_usuario',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
