# Generated by Django 5.1.3 on 2024-11-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_perfil_usuario_perfil_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='id_usuario',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
